# K-Means

* 거리를 계산하기 위해서는 수치형 데이터가 필요하다. 
* 명목형 값은 거리 계산에 대한 이진 값으로 매핑 가능하다.

In [20]:
import numpy as np

In [21]:
import kMeans

## 1. data load

In [22]:
dataMat = []
fr = open('testSet.txt')
for line in fr.readlines():
    curLine = line.strip().split('\t')
    print(curLine)
    fltLine =  map(float, curLine)
    print(fltLine)
    dataMat.append(fltLine)
# print(dataMat)

['1.658985', '4.285136']
['-3.453687', '3.424321']
['4.838138', '-1.151539']
['-5.379713', '-3.362104']
['0.972564', '2.924086']
['-3.567919', '1.531611']
['0.450614', '-3.302219']
['-3.487105', '-1.724432']
['2.668759', '1.594842']
['-3.156485', '3.191137']
['3.165506', '-3.999838']
['-2.786837', '-3.099354']
['4.208187', '2.984927']
['-2.123337', '2.943366']
['0.704199', '-0.479481']
['-0.392370', '-3.963704']
['2.831667', '1.574018']
['-0.790153', '3.343144']
['2.943496', '-3.357075']
['-3.195883', '-2.283926']
['2.336445', '2.875106']
['-1.786345', '2.554248']
['2.190101', '-1.906020']
['-3.403367', '-2.778288']
['1.778124', '3.880832']
['-1.688346', '2.230267']
['2.592976', '-2.054368']
['-4.007257', '-3.207066']
['2.257734', '3.387564']
['-2.679011', '0.785119']
['0.939512', '-4.023563']
['-3.674424', '-2.261084']
['2.046259', '2.735279']
['-3.189470', '1.780269']
['4.372646', '-0.822248']
['-2.579316', '-3.497576']
['1.889034', '5.190400']
['-0.798747', '2.185588']
['2.836520', 

In [23]:
min(dataMat[:, 0])

TypeError: list indices must be integers or slices, not tuple

In [24]:
import pandas as pd
df = pd.read_csv('testSet.csv', header=None)
print(df.head())

          0         1
0  1.658985  4.285136
1 -3.453687  3.424321
2  4.838138 -1.151539
3 -5.379713 -3.362104
4  0.972564  2.924086


In [58]:
# 각 column에서 최소값
print(min(df.iloc[:, 0]))
print(min(df.iloc[:, 1]))

# 각 column에서 최대값
print(max(df.iloc[:, 0]))
print(max(df.iloc[:, 1]))

-5.379713
-4.232586
4.838138
5.1904


## 2. k를 정하고, 한 col에서의 min과 max 사이의 값을 도출

In [77]:
# 80, 2
df.shape
print(df.shape[1])
df_shape = df.shape[1]

# 중심점 만들기 임의의 입력값 k, columns 수
k = 3
centroids = np.mat(np.zeros((k, df_shape)))
print(centroids)


'''
col1 col2
[[0, 0],  k
[0, 0]]   k'''

for j in range(df_shape):
    minJ = min(df.iloc[:, j])
    print("========",j,"번째시작\n한 col에서 최소값:\n ", minJ)
    print("\n한 col에서 최대값:\n ", max(df.iloc[:, j]))
    # 한 칼럼에서 min, max을 구한후
    # 최소값 최대값으로 범위를 구한다. 
    
    rangeJ = float(max(df.iloc[:, j]) - minJ)
    print("\n한 col에서 최소값과 최대값의 range:\n ", rangeJ)
    centroids[:, j] = minJ + rangeJ * np.random.rand(k, 1)
    print("\n임의의 숫자에 min값과 range를 적용:\n", centroids[:, j])
    print("---------", j, "번째 끝!")
#     print(np.random.rand(k, 1))
#     break;
    
print("전체 centroids:\n", centroids)

'''몇개의 k로 군집을 나눌 것인지 정했으면,  
각각 colum의 최소값, 최대값, 범위를 적용한 임의의 숫자를 생성한다.
따라서, 한 컬럼당 3개의(k) 임의의 숫자가 만들어지며, 
column수 * k수 만큼의 숫자가 구성된다.'''

2
[[0. 0.]
 [0. 0.]
 [0. 0.]]
======== 0 번째시작
한 col에서 최소값:
  -5.379713

한 col에서 최대값:
  4.838138

한 col에서 최소값과 최대값의 range:
  10.217851

임의의 숫자에 min값과 range를 적용:
 [[ 0.52540893]
 [-4.28349879]
 [-4.75165236]]
--------- 0 번째 끝!
======== 1 번째시작
한 col에서 최소값:
  -4.232586

한 col에서 최대값:
  5.1904

한 col에서 최소값과 최대값의 range:
  9.422986000000002

임의의 숫자에 min값과 range를 적용:
 [[4.76112478]
 [3.47660601]
 [4.26347426]]
--------- 1 번째 끝!
전체 centroids:
 [[ 0.52540893  4.76112478]
 [-4.28349879  3.47660601]
 [-4.75165236  4.26347426]]


'몇개의 k로 군집을 나눌 것인지 정했으면,  \n각각 colum의 최소값, 최대값, 범위를 적용한 임의의 숫자를 생성한다.\n따라서, 한 컬럼당 3개의(k) 임의의 숫자가 만들어지며, \ncolumn수 * k수 만큼의 숫자가 구성된다.'

In [62]:
# matrix 만들기
matrix1 = np.mat(np.zeros((4, 2)))
print(matrix1)

matrix1[:, 0] = -5.379713 + 10.217851 * np.random.rand(4, 1)
print(matrix1[:, 0])
print(matrix1)

# 중심점 계산 방법
random_matrix = np.random.rand(4, 1)
print("===================")
print(random_matrix)
print(10.217851 * random_matrix)
print(-5.379713 + 10.217851 * random_matrix)

# k개의 중심점을 임의의 값을 생성후, min값과 범위를 이용해서 만든다.?

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[-2.8853821 ]
 [ 0.5291239 ]
 [-3.6717946 ]
 [ 4.18379999]]
[[-2.8853821   0.        ]
 [ 0.5291239   0.        ]
 [-3.6717946   0.        ]
 [ 4.18379999  0.        ]]
[[0.46894591]
 [0.45218993]
 [0.49991519]
 [0.59472898]]
[[4.79161942]
 [4.62040935]
 [5.10805889]
 [6.07685208]]
[[-0.58809358]
 [-0.75930365]
 [-0.27165411]
 [ 0.69713908]]


## 3. 거리를 측정한다.

In [93]:
import numpy as np

df.iloc[0]

df.iloc[1]

np.sqrt(sum(np.power(df.iloc[0] - df.iloc[1], 2)))

5.184632816681332

In [99]:
print("각각의vector:\n",df.iloc[0], "\n",df.iloc[1])
print("\nvector1- vector2:\n", df.iloc[0] - df.iloc[1])
print("\nvector 차의 exponential:\n", np.power(df.iloc[0] - df.iloc[1], 2))

각각의vector:
 0    1.658985
1    4.285136
Name: 0, dtype: float64 
 0   -3.453687
1    3.424321
Name: 1, dtype: float64

vector1- vector2:
 0    5.112672
1    0.860815
dtype: float64

vector 차의 exponential:
 0    26.139415
1     0.741002
dtype: float64


In [103]:
#exponential한 값들의 덧셈
print(sum(np.power(df.iloc[0] - df.iloc[1], 2)))

# 최종적으로 행렬의 거리를 구한다.
print(np.sqrt(sum(np.power(df.iloc[0] - df.iloc[1], 2))))

26.880417443809
5.184632816681332


## 10.2 k-평균 군집화 알고리즘

In [107]:
def distEclud(vecA, vecB):
    return np.sqrt(sum(np.power(vecA - vecB, 2)))

In [133]:
# 총 데이터 수
m = df.shape[0]


# [0, 0]이 데이터 수 만큼
clusterAssment = np.mat(np.zeros((m, 2)))

# k개의 중심점을 만든다. k = 4
n = df.shape[1] # column수
k = 4
centroids = np.mat(np.zeros((k, n)))
for j in range(n):
    minJ = min(df.iloc[:, j])
    rangeJ = float(max(df.iloc[:, j]) - minJ)
    centroids[:, j] = minJ + rangeJ * np.random.rand(k, 1)
# centroids

# flag를 생성
clusterChanged = True

# 반복문 구성
while clusterChanged:
    clusterChanged = False
    for i in range(m): # 총 데이터 수만큼
#         minDist = 
        minIndex = -1
        
        for j in range(k):
            # 거리를 구한다.
            print(centroids[j, :])
            print(np.reshape(df.iloc[i, :].as_matrix(), (-1, 2)))
            distJI = np.sqrt(sum(np.power(centroids[j, :]-np.reshape(df.iloc[i, :].as_matrix(), (-1, 2)), 2)))
            # centroids가 col수 * k만큼 만들어졌으면 
            # centroids[j, :]는 첫번째 군집의 임의로 만들어진 col1과 col2의 ..중심값
            print(distJI)
            
#             minDist = 
            if distJI < minDist:
                minDist = distJI
                minIndex = j
                # 가장 작은 거리를 같는 거리값과 
                # 거리값을 만드는데 사용된 k군집의 번호를 기억한다.
        if clusterAssment[i, :] != minIndex:
            clusterChanged = True
        clusterAssment[i, :] = minIndex, minDist**2
        print(centroids)
        for cent in range(k):
            ptsInClust = df

[[-3.0270103 -2.5035107]]
[[1.658985 4.285136]]
[[4.6859953 6.7886467]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [127]:
print(df.iloc[1, :].as_matrix())
np.reshape(df.iloc[1, :].as_matrix(), (-1, 2))

[-3.453687  3.424321]


array([[-3.453687,  3.424321]])

### numpy.power
exponents <br>
1^^3, 2^^3, 4^^3 

In [89]:
x1 = range(6)
x1

range(0, 6)

In [90]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [91]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]

In [92]:
np.power(x1, x2)

array([ 0.,  1.,  8., 27., 16.,  5.])