어떤 영화가 무슨 장르에 속하는지 자동적으로 알아낼 수 있다. <br>
아이템을 분류하기 위해 사용되는 거리측정(distance measurement)의 개념에 대해 설명. 
<br> 예시
```
1. 알려지지 않은 영화에 대한 모든 거리를 구한다. 
2. 거리를 내림차순으로 정렬하여 가장 가까운 k개의 영화를 찾는다. 
영화제목 |  영화 '?'와의 거리
영화1         20.5
영화2         18.7 
영화3         19.2

3. 가장 가까운 영화 3개가 모두 로맨스 영화면 영화는 로맨스 영화로 예측된다. 
```

 

In [10]:
from numpy import *
import operator

In [12]:
from os import listdir

In [17]:
group = array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
labels = ['A', 'A', 'B', 'B']

In [23]:
print(group)
print(labels)

[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
['A', 'A', 'B', 'B']


In [20]:
## kNN

def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()     
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

In [22]:
classify0([0, 0], group, labels, 3)

AttributeError: 'dict' object has no attribute 'iteritems'

## classify0

In [26]:
dataSetSize = group.shape[0]
print(dataSetSize)
# row 갯수가 몇개인지

4


In [38]:

inX = array([[1, 2]])
print(inX.shape)

(1, 2)


In [39]:
# inX가 0,0이면 0 0 0 0 0 0 0 0, inX가 1, 2이면 1 2 1 2 1 2 1 2
print(tile(inX, (dataSetSize, 1)))

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


각각을 만들어서 모두의 row에서 뺀다?

In [35]:
diffMat = tile(inX, (dataSetSize, 1)) - group
print(diffMat)

[[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]


In [44]:
sqDiffMat = diffMat ** 2
print(sqDiffMat)

[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]


In [46]:
# 각 row의 요소들을 더해준다. 
sqDistances = sqDiffMat.sum(axis = 1)
print(sqDistances)

[2.21 2.   0.   0.01]


In [47]:
distances = sqDistances ** 0.5
print(distances)

[1.48660687 1.41421356 0.         0.1       ]


In [48]:
print(distances.argsort())

# 무슨 의미인지 모르겠음. 
# 거리가 0이 최소거리니까 2번째 있던것이 .. 첫번째로 왔다는 소리.. 
# 2번째 자리, 3번째자리, 1번째자리, 0번째 자리

[2 3 1 0]


In [49]:
sortedDistIndicies = distances.argsort()
print(sortedDistIndicies)

[2 3 1 0]


In [53]:
print(labels[sortedDistIndicies[0]]) # 'A' # index 2를 주었다. 
# 즉, labels[2]
print(labels[2])

B
B


In [58]:
print(classCount.get('B', 0))

2


In [59]:
print(classCount)

{'B': 2, 'A': 1}


In [60]:
classCount = {}
for i in range(3): # k = 3 , 거리로 정렬했을 때, 가장 거리가 가까운 3개
    print(i)
    print(labels[sortedDistIndicies[i]])
    voteIlabel = labels[sortedDistIndicies[i]]
    classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
    print(classCount.get(voteIlabel, 0))
    print("====")

0
B
1
====
1
B
2
====
2
A
1
====


In [63]:
sortedClassCount = sorted(classCount.items(),
                         key=operator.itemgetter(1), reverse=True)
print(sortedClassCount)

# Python 3 renamed dict.iteritems -> dict.items

# for result in result3:
#     o = OrderedDict(sorted(result.items(), key=operator.itemgetter(1), reverse=True))

[('B', 2), ('A', 1)]


In [65]:
print(type(sortedClassCount))

<class 'list'>


#### sortedClassCount

In [66]:
temp = [('B', 2), ('A', 1)]

In [67]:
print(temp[0][0])

B


In [68]:

from numpy import *
import operator
from os import listdir

def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()     
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels

def file2matrix(filename):
    fr = open(filename)
    numberOfLines = len(fr.readlines())         #get the number of lines in the file
    returnMat = zeros((numberOfLines,3))        #prepare matrix to return
    classLabelVector = []                       #prepare labels return   
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(int(listFromLine[-1]))
        index += 1
    return returnMat,classLabelVector

def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = zeros(shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - tile(minVals, (m,1))
    normDataSet = normDataSet/tile(ranges, (m,1))   #element wise divide
    return normDataSet, ranges, minVals

def datingClassTest():
    hoRatio = 0.50      #hold out 10%
    datingDataMat,datingLabels = file2matrix('datingTestSet2.txt')       #load data setfrom file
    normMat, ranges, minVals = autoNorm(datingDataMat)
    m = normMat.shape[0]
    numTestVecs = int(m*hoRatio)
    errorCount = 0.0
    for i in range(numTestVecs):
        classifierResult = classify0(normMat[i,:],normMat[numTestVecs:m,:],datingLabels[numTestVecs:m],3)
        print("the classifier came back with: %d, the real answer is: %d" % (classifierResult, datingLabels[i]))
        if (classifierResult != datingLabels[i]): errorCount += 1.0
    print("the total error rate is: %f" % (errorCount/float(numTestVecs)))
    print(errorCount)

def img2vector(filename):
    returnVect = zeros((1,1024))
    fr = open(filename)
    for i in range(32):
        lineStr = fr.readline()
        for j in range(32):
            returnVect[0,32*i+j] = int(lineStr[j])
    return returnVect

def handwritingClassTest():
    hwLabels = []
    trainingFileList = listdir('trainingDigits')           #load the training set
    m = len(trainingFileList)
    trainingMat = zeros((m,1024))
    for i in range(m):
        fileNameStr = trainingFileList[i]
        fileStr = fileNameStr.split('.')[0]     #take off .txt
        classNumStr = int(fileStr.split('_')[0])
        hwLabels.append(classNumStr)
        trainingMat[i,:] = img2vector('trainingDigits/%s' % fileNameStr)
    testFileList = listdir('testDigits')        #iterate through the test set
    errorCount = 0.0
    mTest = len(testFileList)
    for i in range(mTest):
        fileNameStr = testFileList[i]
        fileStr = fileNameStr.split('.')[0]     #take off .txt
        classNumStr = int(fileStr.split('_')[0])
        vectorUnderTest = img2vector('testDigits/%s' % fileNameStr)
        classifierResult = classify0(vectorUnderTest, trainingMat, hwLabels, 3)
        print("the classifier came back with: %d, the real answer is: %d" % (classifierResult, classNumStr))
        if (classifierResult != classNumStr): errorCount += 1.0
    print("\nthe total number of errors is: %d" % errorCount)
    print("\nthe total error rate is: %f" % (errorCount/float(mTest)))

## File 읽기

In [79]:
fr = open('datingTestSet.txt')
# print(fr)
numberOfLines = len(fr.readlines())
print(numberOfLines) # 파일 줄 수를 구한다.
returnMat = zeros((numberOfLines, 3))
print(returnMat)
# print(len(returnMat))
print("Numpy 행렬: ", returnMat.shape)
classLablVector = []
fr = open('datingTestSet.txt')
index = 0
for line in fr.readlines():
    print(line)
    print(line[3])
    break 

1000
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy 행렬:  (1000, 3)
40920	8.326976	0.953952	largeDoses

2


In [13]:
def createDataSet():
    group = array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels
    

In [4]:
# from PCV.classifiers import knn
# from sklearn import neighbors
# from fancyimpute import KNN
import kNN

SyntaxError: invalid syntax (kNN.py, line 71)

In [ ]:
group, labels = kNN.createDaaSet()