In [7]:
from numpy import *

In [9]:
random.rand(4, 4)
# 4 * 4 크기의 행렬

array([[0.11088541, 0.80408376, 0.11316273, 0.31812524],
       [0.06049151, 0.40357404, 0.57349545, 0.06309319],
       [0.54913149, 0.19104644, 0.26264802, 0.7515767 ],
       [0.74030453, 0.15672877, 0.2359713 , 0.98197991]])

In [12]:
print(mat(random.rand(4, 4)))

[[0.83609993 0.45273276 0.58206656 0.85444306]
 [0.88236851 0.96035072 0.02323181 0.25845051]
 [0.87649979 0.0485355  0.70897956 0.67901946]
 [0.93840952 0.8513121  0.49543623 0.45029427]]


In [13]:
randMat = mat(random.rand(4, 4))
print(randMat)
# 역행렬
randMat.I

[[0.74972272 0.45310383 0.32384983 0.23810942]
 [0.61733439 0.50124432 0.00883935 0.465258  ]
 [0.15049779 0.93719002 0.64112818 0.929273  ]
 [0.32726006 0.75182404 0.09592672 0.84452797]]


matrix([[ -72.70069745,  136.3485163 ,   51.49265657, -111.27784423],
        [ 317.63236412, -585.30541635, -224.11843162,  479.50332997],
        [ -93.64394408,  173.49115173,   68.01804063, -144.01887588],
        [-243.95717423,  448.51424359,  171.83727843, -366.20466192]])